use pyo3::exceptions::{PyValueError, PyZeroDivisionError};
use pyo3::prelude::*;
use pyo3::{Py, PyAny};

use crate::arith::egcd::inv_mod_i128;
use crate::arith::prime::is_prime_u64;
use crate::group::perm::{Perm, Sn};

/// The residue ring `Z/nZ`.
#[pyclass(frozen, from_py_object)]
#[derive(Clone, Debug)]
pub struct Zn {
    n: u64,
}

/// An element of a fixed residue ring `Z/nZ`.
#[pyclass(frozen, from_py_object)]
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct ZnElem {
    n: u64,
    v: u64,
}

fn canon_mod_i128(k: i128, n: u64) -> u64 {
    let m = n as i128;
    let mut r = k % m;
    if r < 0 {
        r += m;
    }
    r as u64
}

fn gcd_u64(mut a: u64, mut b: u64) -> u64 {
    while b != 0 {
        let r = a % b;
        a = b;
        b = r;
    }
    a
}

#[pymethods]
impl Zn {
    #[new]
    /// Construct the ring modulo `n`.
    pub fn new(n: u64) -> PyResult<Self> {
        if n < 2 {
            return Err(PyValueError::new_err("n must be >= 2 for Zn(n)"));
        }
        Ok(Self { n })
    }

    /// Return the modulus `n`.
    pub fn modulus(&self) -> u64 {
        self.n
    }

    /// Return the additive identity.
    pub fn zero(&self) -> ZnElem {
        ZnElem { n: self.n, v: 0 }
    }

    /// Return the multiplicative identity.
    pub fn one(&self) -> ZnElem {
        ZnElem {
            n: self.n,
            v: 1 % self.n,
        }
    }

    /// Convert an integer to its canonical residue class modulo `n`.
    pub fn elem(&self, k: i128) -> ZnElem {
        ZnElem {
            n: self.n,
            v: canon_mod_i128(k, self.n),
        }
    }

    /// Enumerate all residue classes.
    pub fn elements(&self) -> Vec<ZnElem> {
        (0..self.n).map(|v| ZnElem { n: self.n, v }).collect()
    }

    /// Enumerate all units of `Z/nZ`.
    pub fn units(&self) -> Vec<ZnElem> {
        (0..self.n)
            .filter(|&v| gcd_u64(v, self.n) == 1)
            .map(|v| ZnElem { n: self.n, v })
            .collect()
    }

    /// Enumerate all nonzero zero divisors of `Z/nZ`.
    pub fn zero_divisors(&self) -> Vec<ZnElem> {
        (1..self.n)
            .filter(|&v| gcd_u64(v, self.n) != 1)
            .map(|v| ZnElem { n: self.n, v })
            .collect()
    }

    /// Return whether `a` is invertible.
    pub fn is_unit(&self, a: &ZnElem) -> PyResult<bool> {
        self.check(a)?;
        Ok(gcd_u64(a.v, self.n) == 1)
    }

    /// Return whether `a` is a nonzero zero divisor.
    pub fn is_zero_divisor(&self, a: &ZnElem) -> PyResult<bool> {
        self.check(a)?;
        Ok(a.v != 0 && gcd_u64(a.v, self.n) != 1)
    }

    /// Return whether `Z/nZ` is an integral domain.
    pub fn is_integral_domain(&self) -> bool {
        is_prime_u64(self.n)
    }

    /// Return the permutation of residues induced by `x -> x + b`.
    pub fn add_perm(&self, b: &ZnElem) -> PyResult<Perm> {
        self.check(b)?;
        Ok(Perm::new(
            self.n as usize,
            (0..self.n)
                .map(|x| ((x + b.v) % self.n) as usize)
                .collect(),
        )?)
    }

    /// Return the permutation of residues induced by `x -> a*x`.
    pub fn mul_perm(&self, a: &ZnElem) -> PyResult<Perm> {
        self.check(a)?;
        if !a.is_unit() {
            return Err(PyValueError::new_err(
                "element is not a unit, so x -> a*x is not a permutation",
            ));
        }
        Ok(Perm::new(
            self.n as usize,
            (0..self.n)
                .map(|x| (((a.v as u128) * (x as u128)) % (self.n as u128)) as usize)
                .collect(),
        )?)
    }

    /// Return the affine permutation induced by `x -> a*x + b`.
    pub fn affine_perm(&self, a: &ZnElem, b: &ZnElem) -> PyResult<Perm> {
        self.check(a)?;
        self.check(b)?;
        if !a.is_unit() {
            return Err(PyValueError::new_err(
                "leading coefficient is not a unit, so x -> a*x + b is not a permutation",
            ));
        }
        Ok(Perm::new(
            self.n as usize,
            (0..self.n)
                .map(|x| {
                    ((((a.v as u128) * (x as u128)) + (b.v as u128)) % (self.n as u128)) as usize
                })
                .collect(),
        )?)
    }

    /// Return the permutation representation of the unit group acting by multiplication.
    pub fn unit_group_perms(&self) -> PyResult<Vec<Perm>> {
        self.units().iter().map(|u| self.mul_perm(u)).collect()
    }

    /// Return the size of the subgroup generated by the unit action `x -> u*x`.
    pub fn unit_action_subgroup_size(&self) -> PyResult<usize> {
        Sn::new(self.n as usize)?.subgroup_size(self.unit_group_perms()?)
    }

    /// Return the orbit decomposition of residues under the unit action `x -> u*x`.
    pub fn unit_action_orbits(&self) -> PyResult<Vec<Vec<usize>>> {
        Sn::new(self.n as usize)?.orbits(self.unit_group_perms()?)
    }

    /// Return the stabilizer subgroup of `point` under the unit action `x -> u*x`.
    pub fn unit_action_stabilizer(&self, point: usize) -> PyResult<Vec<Perm>> {
        Ok(Sn::new(self.n as usize)?
            .stabilizer(point, self.unit_group_perms()?)?
            .elements())
    }

    /// Return the size of the stabilizer of `point` under the unit action `x -> u*x`.
    pub fn unit_action_stabilizer_size(&self, point: usize) -> PyResult<usize> {
        Sn::new(self.n as usize)?.stabilizer_size(point, self.unit_group_perms()?)
    }

    /// Return whether the unit action is transitive on all residues.
    pub fn is_unit_action_transitive(&self) -> PyResult<bool> {
        Sn::new(self.n as usize)?.is_transitive(self.unit_group_perms()?)
    }

    /// Return `a + b`.
    pub fn add(&self, a: &ZnElem, b: &ZnElem) -> PyResult<ZnElem> {
        self.check(a)?;
        self.check(b)?;
        Ok(ZnElem {
            n: self.n,
            v: (a.v + b.v) % self.n,
        })
    }

    /// Return `-a`.
    pub fn neg(&self, a: &ZnElem) -> PyResult<ZnElem> {
        self.check(a)?;
        Ok(if a.v == 0 {
            a.clone()
        } else {
            ZnElem {
                n: self.n,
                v: self.n - a.v,
            }
        })
    }

    /// Return `a - b`.
    pub fn sub(&self, a: &ZnElem, b: &ZnElem) -> PyResult<ZnElem> {
        self.add(a, &self.neg(b)?)
    }

    /// Return `a * b`.
    pub fn mul(&self, a: &ZnElem, b: &ZnElem) -> PyResult<ZnElem> {
        self.check(a)?;
        self.check(b)?;
        let prod = (a.v as u128) * (b.v as u128);
        Ok(ZnElem {
            n: self.n,
            v: (prod % (self.n as u128)) as u64,
        })
    }

    /// Return the multiplicative inverse of `a` when it exists.
    pub fn inv(&self, a: &ZnElem) -> PyResult<ZnElem> {
        self.check(a)?;
        if a.v == 0 {
            return Err(PyZeroDivisionError::new_err(
                "0 has no multiplicative inverse in Zn",
            ));
        }
        let inv = inv_mod_i128(a.v as i128, self.n as i128)
            .ok_or_else(|| PyValueError::new_err("element is not a unit in Zn"))?;
        Ok(ZnElem {
            n: self.n,
            v: inv as u64,
        })
    }

    /// Return `a^e`, allowing negative exponents for units.
    pub fn pow(&self, a: &ZnElem, e: i128) -> PyResult<ZnElem> {
        self.check(a)?;
        if e == 0 {
            return Ok(self.one());
        }
        if e < 0 {
            let inv = self.inv(a)?;
            return self.pow(&inv, -e);
        }

        let mut exp = e as u64;
        let mut result: u64 = 1 % self.n;
        let mut base: u64 = a.v;

        while exp > 0 {
            if (exp & 1) == 1 {
                result = ((result as u128 * base as u128) % (self.n as u128)) as u64;
            }
            exp >>= 1;
            if exp > 0 {
                base = ((base as u128 * base as u128) % (self.n as u128)) as u64;
            }
        }

        Ok(ZnElem {
            n: self.n,
            v: result,
        })
    }

    fn check(&self, a: &ZnElem) -> PyResult<()> {
        if a.n != self.n {
            Err(PyValueError::new_err("Mixed moduli / parents"))
        } else {
            Ok(())
        }
    }
}

#[pymethods]
impl ZnElem {
    /// Return the canonical representative in `0..n-1`.
    pub fn value(&self) -> u64 {
        self.v
    }

    /// Return whether this element is zero.
    pub fn is_zero(&self) -> bool {
        self.v == 0
    }

    /// Return whether this element is a unit.
    pub fn is_unit(&self) -> bool {
        gcd_u64(self.v, self.n) == 1
    }

    /// Return whether this element is a nonzero zero divisor.
    pub fn is_zero_divisor(&self) -> bool {
        self.v != 0 && gcd_u64(self.v, self.n) != 1
    }

    /// Return `False` only for zero.
    pub fn __bool__(&self) -> bool {
        self.v != 0
    }

    /// Return a human-readable representation.
    pub fn __repr__(&self) -> String {
        format!("{} (mod {})", self.v, self.n)
    }

    /// Convert to the canonical integer representative.
    pub fn __int__(&self) -> u64 {
        self.v
    }

    /// Support `==` and `!=` for elements with the same modulus.
    pub fn __richcmp__(&self, other: &ZnElem, op: pyo3::basic::CompareOp) -> PyResult<bool> {
        if self.n != other.n {
            return Ok(false);
        }
        match op {
            pyo3::basic::CompareOp::Eq => Ok(self.v == other.v),
            pyo3::basic::CompareOp::Ne => Ok(self.v != other.v),
            _ => Err(PyValueError::new_err("Only == and != supported")),
        }
    }

    fn check_same_n(&self, other: &ZnElem) -> PyResult<()> {
        if self.n != other.n {
            Err(PyValueError::new_err("Mixed moduli / parents"))
        } else {
            Ok(())
        }
    }

    fn canon_int(&self, k: i128) -> u64 {
        canon_mod_i128(k, self.n)
    }

    fn add_v(&self, a: u64, b: u64) -> u64 {
        (a + b) % self.n
    }

    fn mul_v(&self, a: u64, b: u64) -> u64 {
        let prod = (a as u128) * (b as u128);
        (prod % (self.n as u128)) as u64
    }

    fn inv_v(&self, a: u64) -> PyResult<u64> {
        if a == 0 {
            return Err(PyZeroDivisionError::new_err(
                "0 has no multiplicative inverse in Zn",
            ));
        }
        let inv = inv_mod_i128(a as i128, self.n as i128)
            .ok_or_else(|| PyValueError::new_err("element is not a unit in Zn"))?;
        Ok(inv as u64)
    }

    fn pow_v(&self, base: u64, exp: i128) -> PyResult<u64> {
        if exp == 0 {
            return Ok(1 % self.n);
        }
        if exp < 0 {
            let inv = self.inv_v(base)?;
            return self.pow_v(inv, -exp);
        }

        let mut e = exp as u64;
        let mut result: u64 = 1 % self.n;
        let mut b: u64 = base % self.n;

        while e > 0 {
            if (e & 1) == 1 {
                result = self.mul_v(result, b);
            }
            e >>= 1;
            if e > 0 {
                b = self.mul_v(b, b);
            }
        }
        Ok(result)
    }

    /// Return the multiplicative inverse when it exists.
    pub fn inv(&self) -> PyResult<ZnElem> {
        Ok(ZnElem {
            n: self.n,
            v: self.inv_v(self.v)?,
        })
    }

    /// Return the additive inverse.
    pub fn __neg__(&self) -> ZnElem {
        if self.v == 0 {
            self.clone()
        } else {
            ZnElem {
                n: self.n,
                v: self.n - self.v,
            }
        }
    }

    /// Add two ring elements.
    pub fn __add__(&self, other: &ZnElem) -> PyResult<ZnElem> {
        self.check_same_n(other)?;
        Ok(ZnElem {
            n: self.n,
            v: self.add_v(self.v, other.v),
        })
    }

    /// Subtract two ring elements.
    pub fn __sub__(&self, other: &ZnElem) -> PyResult<ZnElem> {
        self.check_same_n(other)?;
        let neg = if other.v == 0 { 0 } else { self.n - other.v };
        Ok(ZnElem {
            n: self.n,
            v: self.add_v(self.v, neg),
        })
    }

    /// Multiply two ring elements.
    pub fn __mul__(&self, other: &ZnElem) -> PyResult<ZnElem> {
        self.check_same_n(other)?;
        Ok(ZnElem {
            n: self.n,
            v: self.mul_v(self.v, other.v),
        })
    }

    /// Divide by an invertible element.
    pub fn __truediv__(&self, other: &ZnElem) -> PyResult<ZnElem> {
        self.check_same_n(other)?;
        let inv = self.inv_v(other.v)?;
        Ok(ZnElem {
            n: self.n,
            v: self.mul_v(self.v, inv),
        })
    }

    /// Support `a ** exp` and `pow(a, exp)`.
    pub fn __pow__(&self, exp: i128, modulo: Option<Py<PyAny>>) -> PyResult<ZnElem> {
        if modulo.is_some() {
            return Err(PyValueError::new_err(
                "3-argument pow(a, e, m) is not supported for ZnElem",
            ));
        }
        Ok(ZnElem {
            n: self.n,
            v: self.pow_v(self.v, exp)?,
        })
    }

    /// Support `int + ZnElem`.
    pub fn __radd__(&self, other: i128) -> PyResult<ZnElem> {
        let ov = self.canon_int(other);
        Ok(ZnElem {
            n: self.n,
            v: self.add_v(ov, self.v),
        })
    }

    /// Support `int - ZnElem`.
    pub fn __rsub__(&self, other: i128) -> PyResult<ZnElem> {
        let ov = self.canon_int(other);
        let neg_self = if self.v == 0 { 0 } else { self.n - self.v };
        Ok(ZnElem {
            n: self.n,
            v: self.add_v(ov, neg_self),
        })
    }

    /// Support `int * ZnElem`.
    pub fn __rmul__(&self, other: i128) -> PyResult<ZnElem> {
        let ov = self.canon_int(other);
        Ok(ZnElem {
            n: self.n,
            v: self.mul_v(ov, self.v),
        })
    }

    /// Support `int / ZnElem` inside `Z/nZ`.
    pub fn __rtruediv__(&self, other: i128) -> PyResult<ZnElem> {
        let ov = self.canon_int(other);
        let inv = self.inv_v(self.v)?;
        Ok(ZnElem {
            n: self.n,
            v: self.mul_v(ov, inv),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zn_requires_modulus_at_least_two() {
        assert!(Zn::new(2).is_ok());
        assert!(Zn::new(1).is_err());
    }

    #[test]
    fn zn_canonicalizes_negatives() {
        let z = Zn::new(8).unwrap();
        assert_eq!(z.elem(-1).v, 7);
        assert_eq!(z.elem(-9).v, 7);
        assert_eq!(z.elem(9).v, 1);
    }

    #[test]
    fn zn_units_are_detected() {
        let z = Zn::new(8).unwrap();
        let units: Vec<u64> = z.units().into_iter().map(|a| a.v).collect();
        assert_eq!(units, vec![1, 3, 5, 7]);
        assert!(z.is_unit(&z.elem(3)).unwrap());
        assert!(!z.is_unit(&z.elem(6)).unwrap());
    }

    #[test]
    fn zn_zero_divisors_are_detected() {
        let z = Zn::new(12).unwrap();
        let zero_divisors: Vec<u64> = z.zero_divisors().into_iter().map(|a| a.v).collect();
        assert_eq!(zero_divisors, vec![2, 3, 4, 6, 8, 9, 10]);
        assert!(z.is_zero_divisor(&z.elem(6)).unwrap());
        assert!(!z.is_zero_divisor(&z.zero()).unwrap());
        assert!(!z.is_zero_divisor(&z.elem(5)).unwrap());
    }

    #[test]
    fn zn_integral_domain_matches_prime_modulus() {
        assert!(Zn::new(7).unwrap().is_integral_domain());
        assert!(!Zn::new(12).unwrap().is_integral_domain());
    }

    #[test]
    fn zn_add_perm_matches_translation() {
        let z = Zn::new(5).unwrap();
        let p = z.add_perm(&z.elem(2)).unwrap();
        assert_eq!(p.as_images(), vec![2, 3, 4, 0, 1]);
        assert_eq!(p.order(), 5);
    }

    #[test]
    fn zn_mul_perm_exists_exactly_for_units() {
        let z = Zn::new(12).unwrap();
        let p = z.mul_perm(&z.elem(5)).unwrap();
        assert_eq!(p.as_images(), vec![0, 5, 10, 3, 8, 1, 6, 11, 4, 9, 2, 7]);
        assert_eq!(p.order(), 2);
        assert!(z.mul_perm(&z.elem(6)).is_err());
    }

    #[test]
    fn zn_affine_perm_composes_additive_and_multiplicative_actions() {
        let z = Zn::new(7).unwrap();
        let a = z.elem(3);
        let b = z.elem(2);

        let mul = z.mul_perm(&a).unwrap();
        let add = z.add_perm(&b).unwrap();
        let affine = z.affine_perm(&a, &b).unwrap();

        assert_eq!(add.compose(&mul).unwrap(), affine);
    }

    #[test]
    fn zn_unit_group_perms_has_one_perm_per_unit() {
        let z = Zn::new(10).unwrap();
        let perms = z.unit_group_perms().unwrap();
        assert_eq!(perms.len(), z.units().len());
    }

    #[test]
    fn zn_unit_action_helpers_match_expected_orbits() {
        let z = Zn::new(12).unwrap();
        assert_eq!(z.unit_action_subgroup_size().unwrap(), 4);
        assert_eq!(
            z.unit_action_orbits().unwrap(),
            vec![
                vec![0],
                vec![1, 5, 7, 11],
                vec![2, 10],
                vec![3, 9],
                vec![4, 8],
                vec![6],
            ]
        );
        assert!(!z.is_unit_action_transitive().unwrap());
        assert_eq!(z.unit_action_stabilizer_size(1).unwrap(), 1);
        assert_eq!(z.unit_action_stabilizer_size(6).unwrap(), 4);
    }

    #[test]
    fn zn_inverse_exists_only_for_units() {
        let z = Zn::new(10).unwrap();
        let a = z.elem(3);
        let inv = z.inv(&a).unwrap();
        assert_eq!(z.mul(&a, &inv).unwrap().v, 1);
        assert!(z.inv(&z.elem(2)).is_err());
    }

    #[test]
    fn zn_negative_power_requires_unit() {
        let z = Zn::new(9).unwrap();
        assert_eq!(z.pow(&z.elem(2), -1).unwrap().v, 5);
        assert!(z.pow(&z.elem(3), -1).is_err());
    }

    #[test]
    fn zn_elem_operator_mixing_works() {
        let z = Zn::new(12).unwrap();
        let a = z.elem(7);
        let b = z.elem(11);
        assert_eq!((a.__add__(&b).unwrap()).v, 6);
        assert_eq!((a.__mul__(&b).unwrap()).v, 5);
        assert_eq!(a.__radd__(5).unwrap().v, 0);
        assert_eq!(a.__rmul__(5).unwrap().v, 11);
    }
}
