import algebrapy as alg


def describe(c):
    print(c)
    print("  elements:   ", c.elements())
    print("  generators: ", c.generators())
    print("  element orders:")
    for k in c.elements():
        print(f"    ord({k}) = {c.element_order(k)}")
    print()
    print("  subgroup lattice:")
    for gen, elems in c.subgroups():
        size = len(elems)
        print(f"    <{gen}> ≅ C{size}  ->  {elems}")
    print()


print("=== C8 ===")
describe(alg.Cn(8))

print("=== C12 ===")
describe(alg.Cn(12))

print("=== C7 (prime order — simple group) ===")
c7 = alg.Cn(7)
print(c7)
print("  elements:   ", c7.elements())
print("  generators: ", c7.generators())
print("  every nonzero element generates the whole group")
for k in range(1, 7):
    g, elems = c7.subgroup([k])
    assert len(elems) == 7, "C7 is simple"
print("  subgroups:  ", [f"<{g}> (size {len(e)})" for g, e in c7.subgroups()])

print()
print("=== Group operations ===")
c = alg.Cn(12)
print("C12 operations:")
print("  7 + 8 =", c.op(7, 8))
print("  inv(5) =", c.inv(5))
print("  5·3    =", c.pow(5, 3))
print("  5·(-1) =", c.pow(5, -1))

print()
print("=== Is 5 a generator of C12? ===")
print("  C12.is_generator(5) =", c.is_generator(5))
print("  C12.is_generator(4) =", c.is_generator(4))

print()
print("=== Subgroup generated by [8] ===")
gens, elems = c.subgroup([8])
print("  generators:", gens)
print("  elements:", elems)

print()
print("=== Subgroup generated by [6, 4] ===")
gens, elems = c.subgroup([6, 4])
print("  generators:", gens)
print("  elements:", elems)
print("  (gcd(6, 4, 12) = 2, so these generate <2>)")
