import algebrapy as alg


def show_perm(label, perm):
    print(label)
    print("  cycle notation =", perm.cycle_notation())
    print("  cycle type =", perm.cycle_type())
    print("  order =", perm.order())
    print()


F = alg.Fp(7)
g = F.elem(3)  # primitive in GF(7)
b = F.elem(1)

add = F.add_perm(b)
mul = F.mul_perm(g)
aff = F.affine_perm(g, b)
sn = alg.Sn(F.modulus())

print("GF(7)")
print("elements =", F.elements())
print("generator =", g, "with multiplicative order", g.mul_order())
print()

show_perm("translation x -> x + 1", add)
show_perm("multiplication x -> 3x", mul)
show_perm("affine map x -> 3x + 1", aff)

print("subgroup generated by x -> 3x")
print("  size =", sn.subgroup_size([mul]))
print("  orbits =", sn.orbits([mul]))
print("  orbit of 1 =", sn.orbit(1, [mul]))
print("  stabilizer size of 1 =", sn.stabilizer_size(1, [mul]))
print("  transitive?", sn.is_transitive([mul]))
print()

print("subgroup generated by x -> x + 1 and x -> 3x")
print("  size =", sn.subgroup_size([add, mul]))
print("  orbits =", sn.orbits([add, mul]))
print("  transitive?", sn.is_transitive([add, mul]))
