import algebrapy as alg


def show_perm(label, perm):
    print(label)
    print("  cycle notation =", perm.cycle_notation())
    print("  cycle type =", perm.cycle_type())
    print("  order =", perm.order())
    print()


K = alg.Fq(2, [1, 1, 0, 1])  # GF(2^3)
g = K.primitive_elements()[0]
b = K.elem([1])

add = K.add_perm(b)
mul = K.mul_perm(g)
aff = K.affine_perm(g, b)
sn = alg.Sn(K.size())

print("GF(2^3)")
print("primitive element =", g)
print("order(g) =", K.mul_order(g))
print()

show_perm("translation x -> x + 1", add)
show_perm("multiplication x -> g*x", mul)
show_perm("affine map x -> g*x + 1", aff)

print("subgroup generated by x -> g*x")
print("  size =", sn.subgroup_size([mul]))
print("  orbits =", sn.orbits([mul]))
print("  orbit of 1 =", sn.orbit(1, [mul]))
print("  stabilizer size of 1 =", sn.stabilizer_size(1, [mul]))
print("  transitive?", sn.is_transitive([mul]))
print()

print("subgroup generated by x -> x + 1 and x -> g*x")
print("  size =", sn.subgroup_size([add, mul]))
print("  orbits =", sn.orbits([add, mul]))
print("  transitive?", sn.is_transitive([add, mul]))
print()

print("field convenience wrappers")
print("  multiplicative action subgroup size =", K.multiplicative_action_subgroup_size())
print("  multiplicative action orbits =", K.multiplicative_action_orbits())
print("  stabilizer size of 1 =", K.multiplicative_action_stabilizer_size(1))
print("  stabilizer size of 0 =", K.multiplicative_action_stabilizer_size(0))
print("  transitive?", K.is_multiplicative_action_transitive())
